# Generated by Django 3.1.4 on 2022-04-23 09:00

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='location',
        ),
        migrations.AddField(
            model_name='profile',
            name='experienceStatus',
            field=models.CharField(blank=True, choices=[('B', 'Beginner'), ('I', 'Intermidiate'), ('A', 'Advanced'), ('T', 'Trainer')], default='B', max_length=30),
        ),
        migrations.AddField(
            model_name='profile',
            name='tennisClub',
            field=models.CharField(blank=True, choices=[('SALK', 'SALK'), ('KTP', 'Kungliga Tennis Planen'), ('STK', 'Solna Tennis Klubb')], default='', max_length=30),
        ),
        migrations.AlterField(
            model_name='profile',
            name='user',
            field=models.OneToOneField(editable=False, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
